apiVersion: v1
kind: Service
metadata: 
  name: mongo-express-service
  namespace: test-mongo-db-ns
spec:
  type: NodePort
  selector: 
    app: mongo-express
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 31313
    protocol: TCP