apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mongo-express
  namespace: test-mongo-db-ns
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: mongo-express
  template:
    metadata: 
      labels:
        app: mongo-express
    spec: 
      containers:
      - name: mongo-express-container
        image: mongo-express
        env: 
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-db-secret
              key: mongo-db-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-db-secret
              key: mongo-db-root-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongo-db-configmap
              key: database_url
        ports:
        - containerPort: 8081
        resources: