apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mongo-db
  namespace: test-mongo-db-ns
  labels:
    app: mongo-db
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: mongo-db
  template: 
    metadata: 
      labels:
        app: mongo-db
    spec: 
      volumes:
      - name: mongo-db-volume
        persistentVolumeClaim:
          claimName: mongo-db-claim
      containers:
      - name: mongo-db-container
        image: mongo
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-db-secret
              key: mongo-db-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-db-secret
              key: mongo-db-root-password
        volumeMounts:
        - name: mongo-db-volume
          mountPath: /data/db
        ports:
        - containerPort: 27017
        resources: